jam:
  clientAddress: "https://example.com"
  spotifyCallbackURL: "https://example.com/api/v1/auth/callback"

backendImage:
  repository: ghcr.io/jamfactoryapp/jamfactory-backend:latest
  pullPolicy: Always

webImage:
  repository: ghcr.io/jamfactoryapp/jamfactory-web:latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  host: example.com
  tls:
    - secretName: jamfactory-tls
      hosts:
        - example.com
