apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    name: {{ .Release.Name }}-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    name: {{ .Release.Name }}-redis
