apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    name: {{ .Release.Name }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    name: {{ .Release.Name }}-backend
