{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  tls:
  {{- toYaml . | nindent 8 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: 80
  {{ end }}
